{% set name = "lhcb-simpletools" %}
{% set version = "2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/cofitzpa/simpletools/archive/v{{ version }}.tar.gz
  sha256: c9b57458bf2078bdacb87dc2ef50c3cb9b85acc382a352c4c0a7d6ace22e116f
  patches:
    - 0001-Fix-linking-for-macOS.patch
    - 0002-Fix-random_shuffle.patch
    - 0003-Fix-includes-for-ROOT-6.22.patch

build:
  number: 8
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
    - cmake
    - make
  host:
    - root_base
    - root-binaries
    - root-dependencies
    - boost-cpp
  run_constrained:
    - __osx >={{ MACOSX_DEPLOYMENT_TARGET|default("10.9") }}  # [osx]

test:
  requires:
    - scikit-hep-testdata
  commands:
    - curl -LO http://opendata.cern.ch/record/212/files/HEPTutorial_0.tar
    - tar xvf HEPTutorial_0.tar
    - FN=HEPTutorial/files/data.root
    # Don't use skhep_testdata for now:
    # https://github.com/scikit-hep/scikit-hep-testdata/pull/42
    # - FN=$(python -m skhep_testdata cms_hep_2012_tutorial/data.root)
    - cutapplier "${FN}" events "NJet>2" test_cut.root
    - cuttester "${FN}" events "${RECIPE_DIR}/cuts.txt"
    - tuplesampler "${FN}" events 0.3 1234 test1.root test2.root
    - columnmaker "${FN}" events "Jet_E**2" Jet_E2 test_col.root
    - which stacker
    - which stackergen
    - which crop

about:
  home: https://github.com/cofitzpa/simpletools
  license: GPL-2.0-only
  license_file: LICENSE
  summary: 'Handy command line tools for ntuple manipulation and analysis'
  doc_url: https://cds.cern.ch/record/1223091
  dev_url: https://github.com/cofitzpa/simpletools

extra:
  recipe-maintainers:
    - chrisburr
