travis:
  secure:
    BINSTAR_TOKEN: p8fCSJaT0OnM3Bh50+THjDqHN9XCxw+z4DgM99ER85iFvIo2H0bpRFR8AboWdG+rWIE01mMRXCla9TpHYf23TI5WVADipTypyohV7su6wfAqdc4ri/OZuT23WxNHVtIeSS4Ir+xIinIk8XDOpqHG3S05UtPtc1449TcoZvs/EO3AMHTJ64dasatnatp8F2UT5jyu+1Mt64cb7i61/2PiyXZpt7tkCPTMipwhbkgsQYnPAU3nkZSzGWp/ZinuBVH5EzHXAzt2XjgDzv9IYO4LjwqnjlSqNdvslBRGr5oP+WMphWUyTyQe0tKG2r3sgeucS8Vf1pbNSmzXes8ifjQ4rr73sVaGWP3laqDavuKH2PyKHPTWULd1p2GzjQhoW15OGYVQRX6PSWNwfnDvliCsakB9ETLhK+eOv6qiF35a2TZQAPoFJeHtvAT0S6+71/OdSmld6g44juYX3KS0JOvBoBloQKNPaDtVJAozwdrCqeNVnpvOOSCQH4J3BmjTY1OQ4718WQRg/m90E95c6HCHoJe4qhqIhEl6yUOd17x0sV9SPUmm67y1BRr8uWLQxy59mwdBWn4trXviGFCSA2vxAOykd70x9WmJtLKAipl53G0zC9uONoa5WDUjo6qCn5mm7NTAF2qIWeqYc6xNkEEQDWDFJUefJyzzV2HwSn52NfI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
